apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantlink-mobile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plantlink-mobile
  template:
    metadata:
      labels:
        app: plantlink-mobile
    spec:
      containers:
      - name: plantlink-mobile
        image: registry.digitalocean.com/aisyahfyp-registry/plantlink-mobile:latest
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          value: "django-insecure-change-this-in-production"
        - name: DEBUG
          value: "False"
        - name: ALLOWED_HOSTS
          value: "plantlink.xyz,www.plantlink.xyz,129.212.209.21"
        - name: PLANTFEED_BASE_URL
          value: "http://plantfeed.xyz"
        - name: PLANTLINK_NGROK_URL
          value: "http://plantlink.xyz"
---
apiVersion: v1
kind: Service
metadata:
  name: plantlink-mobile
spec:
  selector:
    app: plantlink-mobile
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer